name: Windows 11 with Tailscale Access (Fixed)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  windows11-runner:
    name: Run on Windows 11 (Tailscale Ready)
    runs-on: windows-latest

    steps:
      - name: 🧩 Checkout Repository
        uses: actions/checkout@v4

      - name: ⚙️ Install Tailscale via Chocolatey
        shell: pwsh
        run: |
          Write-Host "Installing Tailscale..."
          choco install tailscale -y
          Write-Host "Installation complete."
          Write-Host "Adding Tailscale to PATH..."
          $env:Path += ";C:\Program Files\Tailscale"
          if (Test-Path "C:\Program Files\Tailscale\tailscale.exe") {
            Write-Host "✅ Tailscale found."
          } else {
            Write-Host "❌ Tailscale not found."
          }
          tailscale version

      - name: 🔐 Authenticate to Tailscale
        shell: pwsh
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
        run: |
          Write-Host "Bringing Tailscale up..."
          $env:Path += ";C:\Program Files\Tailscale"
          tailscale up --authkey $env:TAILSCALE_AUTHKEY --hostname "github-runner-win11" --accept-routes=true
          tailscale status
          tailscale ip -4

      - name: 🚀 Run Custom Commands
        shell: pwsh
        run: |
          $env:Path += ";C:\Program Files\Tailscale"
          Write-Host "Connected successfully to Tailscale network!"
          dir

      - name: 🧹 Logout from Tailscale
        if: always()
        shell: pwsh
        run: |
          $env:Path += ";C:\Program Files\Tailscale"
          Write-Host "Logging out from Tailscale..."
          tailscale logout
          Write-Host "Tailscale session ended."
