name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure Core RDP Settings
        shell: pwsh
        run: |
          # Enable Remote Desktop and disable Network Level Authentication (if needed)
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
                             -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "SecurityLayer" -Value 0 -Force

          # Remove any existing rule with the same name to avoid duplication
          netsh advfirewall firewall delete rule name="RDP-Tailscale" 
           
          # For testing, allow any incoming connection on port 3389
          netsh advfirewall firewall add rule name="RDP-Tailscale" `
            dir=in action=allow protocol=TCP localport=3389

          # (Optional) Restart the Remote Desktop service to ensure changes take effect
          Restart-Service -Name TermService -Force

      - name: Create RDP User with Secure Password
        shell: pwsh
        run: |
          Add-Type -AssemblyName System.Security
          $charSet = @{
              Upper   = [char[]](65..90)      # A-Z
              Lower   = [char[]](97..122)     # a-z
              Number  = [char[]](48..57)      # 0-9
              Special = ([char[]](33..47) + [char[]](58..64) + 
                         [char[]](91..96) + [char[]](123..126)) # Special characters
          }
          $rawPassword = @()
          $rawPassword += $charSet.Upper | Get-Random -Count 4
          $rawPassword += $charSet.Lower | Get-Random -Count 4
          $rawPassword += $charSet.Number | Get-Random -Count 4
          $rawPassword += $charSet.Special | Get-Random -Count 4
          $password = -join ($rawPassword | Sort-Object { Get-Random })
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          
          # Remove existing user if exists
          Remove-LocalUser -Name "RDP" -ErrorAction SilentlyContinue
          
          New-LocalUser -Name "RDP" -Password $securePass -AccountNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "RDP"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"
           
          echo "RDP_PASSWORD=$password" >> $env:GITHUB_ENV
           
          if (-not (Get-LocalUser -Name "RDP")) {
              Write-Error "User creation failed"
              exit 1
          }

      - name: Install Tailscale
        shell: pwsh
        run: |
          $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi"
          $installerPath = "$env:TEMP\tailscale.msi"
           
          Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath
          Start-Process msiexec.exe -ArgumentList "/i", "`"$installerPath`"", "/quiet", "/norestart" -Wait
          Remove-Item $installerPath -Force
          
          # Wait for installation to complete
          Start-Sleep -Seconds 10

      - name: Establish Tailscale Connection
        shell: pwsh
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          # Wait for Tailscale service to be ready
          Start-Sleep -Seconds 10
          
          # Bring up Tailscale with the provided auth key and set a unique hostname
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=$env:TAILSCALE_AUTH_KEY --hostname=gh-runner-$env:GITHUB_RUN_ID
           
          # Wait for Tailscale to assign an IP
          $tsIP = $null
          $retries = 0
          while (-not $tsIP -and $retries -lt 10) {
              try {
                  $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
                  if ($tsIP -and $tsIP.Trim()) {
                      break
                  }
              } catch {
                  Write-Host "Waiting for Tailscale IP... Attempt $($retries + 1)"
              }
              Start-Sleep -Seconds 5
              $retries++
          }
           
          if (-not $tsIP -or -not $tsIP.Trim()) {
              Write-Error "Tailscale IP not assigned. Exiting."
              exit 1
          }
          
          $tsIP = $tsIP.Trim()
          echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV
          Write-Host "Tailscale IP: $tsIP"

      - name: Verify RDP Accessibility
        shell: pwsh
        run: |
          Write-Host "Tailscale IP: $env:TAILSCALE_IP"
           
          # Test local RDP port instead of Tailscale IP
          $testResult = Test-NetConnection -ComputerName localhost -Port 3389
          if (-not $testResult.TcpTestSucceeded) {
              Write-Error "TCP connection to RDP port 3389 failed locally"
              exit 1
          }
          Write-Host "TCP connectivity successful!"

      - name: Display Connection Information
        shell: pwsh
        run: |
          Write-Host "`n=== RDP ACCESS ==="
          Write-Host "Address: $env:TAILSCALE_IP"
          Write-Host "Username: RDP"
          Write-Host "Password: $env:RDP_PASSWORD"
          Write-Host "==================`n"
          
          # Get and display additional Tailscale info
          & "$env:ProgramFiles\Tailscale\tailscale.exe" status
          & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4

      - name: Maintain Connection
        shell: pwsh
        run: |
          Write-Host "RDP session active - Keeping runner alive for 60 minutes"
          Write-Host "Connect using:"
          Write-Host "IP: $env:TAILSCALE_IP"
          Write-Host "User: RDP"
          Write-Host "Password: $env:RDP_PASSWORD"
          Write-Host "`nThis session will automatically timeout after 60 minutes"
          
          # Keep runner active for 60 minutes (3600 seconds)
          $startTime = Get-Date
          $timeoutMinutes = 60
          
          while (((Get-Date) - $startTime).TotalMinutes -lt $timeoutMinutes) {
              $elapsed = [math]::Round(((Get-Date) - $startTime).TotalMinutes)
              $remaining = $timeoutMinutes - $elapsed
              Write-Host "[$(Get-Date)] RDP Active - Elapsed: ${elapsed}m, Remaining: ${remaining}m"
              Start-Sleep -Seconds 60
          }
          
          Write-Host "RDP session timeout reached"
